In [1]:
import numpy as np
import random

Manual Dot Product


In [9]:
def sample(a,b):
    result=0
    for i in range(len(a)):
        result+=a[i]*b[i]
    return result

In [10]:
print(sample([1,2,3], [4,5,6]))


32


Vector Operations

In [14]:
def vector_operations(a, b):
    print("Vector A:", a)
    print("Vector B:", b)
    print("Addition:", a + b)
    print("Subtraction:", a - b)
    print("Scalar Multiplication (2 * A):", 2 * a)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
vector_operations(v1, v2)

Vector A: [1 2 3]
Vector B: [4 5 6]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Scalar Multiplication (2 * A): [2 4 6]


Matrix Addition

In [15]:
def matrix_addition(A, B):
    return A + B
A=np.array([[1,2],
            [2,3]])
b=np.array([[9,2],
            [7,3]])
matrix_addition(A,b)

array([[10,  4],
       [ 9,  6]])

#  Random Matrix Generator

In [18]:
def random_matrix(rows, cols):
    return np.random.rand(rows, cols)
random_matrix(3,4)

array([[0.92767668, 0.97808552, 0.48472781, 0.17977727],
       [0.74148958, 0.03992341, 0.5657248 , 0.85452742],
       [0.98928687, 0.18463982, 0.42129014, 0.70208891]])

# Matrix Multiplication (Manual)

In [21]:
import numpy as np

def manual_matrix_multiplication(A, B):
    rows_A = len(A)
    cols_B = len(B[0])
    cols_A = len(A[0])

    # Step 1: empty result matrix (sab 0)
    result = []

    for i in range(rows_A):
        row = []
        for j in range(cols_B):
            sum_val = 0
            for k in range(cols_A):
                sum_val += A[i][k] * B[k][j]
            row.append(sum_val)
        result.append(row)

    return np.array(result)
A=np.array([[1,2],
            [2,3]])
b=np.array([[9,2],
            [7,3]])
manual_matrix_multiplication(A,b)

array([[23,  8],
       [39, 13]])